defmodule OriginsSdk.Identity.ChatConfig do
  @moduledoc """
  Mirror of `Origins.Identity.ChatConfig` over the wire.
  Generated — do not edit by hand.
  """

  @type t :: %__MODULE__{
    available_avatar_ids: list() | nil,
    button_shape: String.t() | nil,
    chat_bubble_color: String.t() | nil,
    chat_bubble_text_color: String.t() | nil,
    chat_button_border_color: String.t() | nil,
    chat_button_color: String.t() | nil,
    chat_button_icon: String.t() | nil,
    chat_button_position: String.t() | nil,
    chat_button_show_icon: boolean() | nil,
    chat_button_text: String.t() | nil,
    chat_button_text_color: String.t() | nil,
    chat_window_title: String.t() | nil,
    created_at: DateTime.t(),
    enable_chat_history: boolean() | nil,
    enable_sound_notifications: boolean() | nil,
    header_style: String.t() | nil,
    id: String.t(),
    inherits_descendant_knowledge: boolean(),
    input_placeholder: String.t() | nil,
    input_style: String.t() | nil,
    origin_entity_id: String.t() | nil,
    podcast_button_border_color: String.t() | nil,
    podcast_button_color: String.t() | nil,
    podcast_button_icon: String.t() | nil,
    podcast_button_shape: String.t() | nil,
    podcast_button_show_icon: boolean() | nil,
    podcast_button_text: String.t() | nil,
    podcast_button_text_color: String.t() | nil,
    podcast_show_brand_logo: boolean() | nil,
    public_profile_button_border_color: String.t() | nil,
    public_profile_button_color: String.t() | nil,
    public_profile_button_icon: String.t() | nil,
    public_profile_button_shape: String.t() | nil,
    public_profile_button_show_icon: boolean() | nil,
    public_profile_button_text: String.t() | nil,
    public_profile_button_text_color: String.t() | nil,
    public_profile_show_brand_logo: boolean() | nil,
    response_delay: integer() | nil,
    send_button_style: String.t() | nil,
    show_ai_message_avatar: boolean() | nil,
    show_brand_logo: boolean() | nil,
    show_close_button: boolean() | nil,
    show_header_avatar: boolean() | nil,
    show_powered_by: boolean() | nil,
    show_typing_indicator: boolean() | nil,
    updated_at: DateTime.t(),
    use_chat_button_for_podcast: boolean() | nil,
    use_chat_button_for_public_profile: boolean() | nil,
    user_bubble_color: String.t() | nil,
    user_bubble_text_color: String.t() | nil,
    welcome_message: String.t() | nil,
    window_animation: String.t() | nil,
    window_border_radius: String.t() | nil,
    window_position_mode: String.t() | nil,
    window_size: String.t() | nil
    }

  defstruct [
    :available_avatar_ids,
    :button_shape,
    :chat_bubble_color,
    :chat_bubble_text_color,
    :chat_button_border_color,
    :chat_button_color,
    :chat_button_icon,
    :chat_button_position,
    :chat_button_show_icon,
    :chat_button_text,
    :chat_button_text_color,
    :chat_window_title,
    :created_at,
    :enable_chat_history,
    :enable_sound_notifications,
    :header_style,
    :id,
    :inherits_descendant_knowledge,
    :input_placeholder,
    :input_style,
    :origin_entity_id,
    :podcast_button_border_color,
    :podcast_button_color,
    :podcast_button_icon,
    :podcast_button_shape,
    :podcast_button_show_icon,
    :podcast_button_text,
    :podcast_button_text_color,
    :podcast_show_brand_logo,
    :public_profile_button_border_color,
    :public_profile_button_color,
    :public_profile_button_icon,
    :public_profile_button_shape,
    :public_profile_button_show_icon,
    :public_profile_button_text,
    :public_profile_button_text_color,
    :public_profile_show_brand_logo,
    :response_delay,
    :send_button_style,
    :show_ai_message_avatar,
    :show_brand_logo,
    :show_close_button,
    :show_header_avatar,
    :show_powered_by,
    :show_typing_indicator,
    :updated_at,
    :use_chat_button_for_podcast,
    :use_chat_button_for_public_profile,
    :user_bubble_color,
    :user_bubble_text_color,
    :welcome_message,
    :window_animation,
    :window_border_radius,
    :window_position_mode,
    :window_size
  ]

  @primitive_fields ~w(available_avatar_ids button_shape chat_bubble_color chat_bubble_text_color chat_button_border_color chat_button_color chat_button_icon chat_button_position chat_button_show_icon chat_button_text chat_button_text_color chat_window_title created_at enable_chat_history enable_sound_notifications header_style id inherits_descendant_knowledge input_placeholder input_style origin_entity_id podcast_button_border_color podcast_button_color podcast_button_icon podcast_button_shape podcast_button_show_icon podcast_button_text podcast_button_text_color podcast_show_brand_logo public_profile_button_border_color public_profile_button_color public_profile_button_icon public_profile_button_shape public_profile_button_show_icon public_profile_button_text public_profile_button_text_color public_profile_show_brand_logo response_delay send_button_style show_ai_message_avatar show_brand_logo show_close_button show_header_avatar show_powered_by show_typing_indicator updated_at use_chat_button_for_podcast use_chat_button_for_public_profile user_bubble_color user_bubble_text_color welcome_message window_animation window_border_radius window_position_mode window_size)a

  @doc "All primitive field atoms — used when caller passes `fields: :all`."
  def primitive_fields, do: @primitive_fields

  @doc false
  @spec from_json(map() | nil) :: t() | nil
  def from_json(nil), do: nil

  def from_json(map) when is_map(map) do
    %__MODULE__{
      available_avatar_ids: map["available_avatar_ids"],
      button_shape: map["button_shape"],
      chat_bubble_color: map["chat_bubble_color"],
      chat_bubble_text_color: map["chat_bubble_text_color"],
      chat_button_border_color: map["chat_button_border_color"],
      chat_button_color: map["chat_button_color"],
      chat_button_icon: map["chat_button_icon"],
      chat_button_position: map["chat_button_position"],
      chat_button_show_icon: map["chat_button_show_icon"],
      chat_button_text: map["chat_button_text"],
      chat_button_text_color: map["chat_button_text_color"],
      chat_window_title: map["chat_window_title"],
      created_at: OriginsSdk.Internal.decode_datetime(map["created_at"]),
      enable_chat_history: map["enable_chat_history"],
      enable_sound_notifications: map["enable_sound_notifications"],
      header_style: map["header_style"],
      id: map["id"],
      inherits_descendant_knowledge: map["inherits_descendant_knowledge"],
      input_placeholder: map["input_placeholder"],
      input_style: map["input_style"],
      origin_entity_id: map["origin_entity_id"],
      podcast_button_border_color: map["podcast_button_border_color"],
      podcast_button_color: map["podcast_button_color"],
      podcast_button_icon: map["podcast_button_icon"],
      podcast_button_shape: map["podcast_button_shape"],
      podcast_button_show_icon: map["podcast_button_show_icon"],
      podcast_button_text: map["podcast_button_text"],
      podcast_button_text_color: map["podcast_button_text_color"],
      podcast_show_brand_logo: map["podcast_show_brand_logo"],
      public_profile_button_border_color: map["public_profile_button_border_color"],
      public_profile_button_color: map["public_profile_button_color"],
      public_profile_button_icon: map["public_profile_button_icon"],
      public_profile_button_shape: map["public_profile_button_shape"],
      public_profile_button_show_icon: map["public_profile_button_show_icon"],
      public_profile_button_text: map["public_profile_button_text"],
      public_profile_button_text_color: map["public_profile_button_text_color"],
      public_profile_show_brand_logo: map["public_profile_show_brand_logo"],
      response_delay: map["response_delay"],
      send_button_style: map["send_button_style"],
      show_ai_message_avatar: map["show_ai_message_avatar"],
      show_brand_logo: map["show_brand_logo"],
      show_close_button: map["show_close_button"],
      show_header_avatar: map["show_header_avatar"],
      show_powered_by: map["show_powered_by"],
      show_typing_indicator: map["show_typing_indicator"],
      updated_at: OriginsSdk.Internal.decode_datetime(map["updated_at"]),
      use_chat_button_for_podcast: map["use_chat_button_for_podcast"],
      use_chat_button_for_public_profile: map["use_chat_button_for_public_profile"],
      user_bubble_color: map["user_bubble_color"],
      user_bubble_text_color: map["user_bubble_text_color"],
      welcome_message: map["welcome_message"],
      window_animation: map["window_animation"],
      window_border_radius: map["window_border_radius"],
      window_position_mode: map["window_position_mode"],
      window_size: map["window_size"]
    }
  end

  @doc false
  @spec from_list([map()] | nil) :: [t()] | nil
  def from_list(nil), do: nil
  def from_list(list) when is_list(list), do: Enum.map(list, &from_json/1)
end
