defmodule OriginsSdk.Identity.OriginEntity do
  @moduledoc """
  Mirror of `Origins.Identity.OriginEntity` over the wire.
  Generated — do not edit by hand.
  """

  @type t :: %__MODULE__{
    accent_colors: list() | nil,
    ai_generated_summary: String.t() | nil,
    appearance_config: any() | nil,
    banner_key: String.t() | nil,
    banner_url: String.t() | nil,
    categories: list() | nil,
    content_tabs_config: map() | nil,
    content_themes: list() | nil,
    core_values: list() | nil,
    created_at: DateTime.t(),
    description: String.t() | nil,
    engagement_metrics: map() | nil,
    extracted_content: map() | nil,
    guardrails_settings: map() | nil,
    id: String.t(),
    is_active: boolean() | nil,
    is_featured: boolean() | nil,
    is_public: boolean() | nil,
    key_messaging: list() | nil,
    last_website_scrape: DateTime.t() | nil,
    mission_statement: String.t() | nil,
    name: String.t(),
    page_sections_config: map() | nil,
    parent_origin_entity_id: String.t() | nil,
    personality_traits: list() | nil,
    picture_key: String.t() | nil,
    picture_url: String.t() | nil,
    podcast_button_color: String.t() | nil,
    podcast_button_link: String.t() | nil,
    podcast_button_text: String.t() | nil,
    podcast_button_text_color: String.t() | nil,
    podcast_button_visible: boolean() | nil,
    podcast_config: map() | nil,
    podcast_content_settings: map() | nil,
    public_profile_config: any() | nil,
    setup_progress_id: String.t() | nil,
    slug: String.t(),
    social_links: list() | nil,
    target_audience: String.t() | nil,
    title: String.t() | nil,
    tone_of_voice: String.t() | nil,
    updated_at: DateTime.t(),
    voice_config: map() | nil,
    voice_settings: map() | nil,
    website_content: map() | nil,
    youtube_channel_data: map() | nil,
    youtube_channel_id: String.t() | nil,
    youtube_content_settings: map() | nil,
    youtube_sync_settings: map() | nil
    }

  defstruct [
    :accent_colors,
    :ai_generated_summary,
    :appearance_config,
    :banner_key,
    :banner_url,
    :categories,
    :content_tabs_config,
    :content_themes,
    :core_values,
    :created_at,
    :description,
    :engagement_metrics,
    :extracted_content,
    :guardrails_settings,
    :id,
    :is_active,
    :is_featured,
    :is_public,
    :key_messaging,
    :last_website_scrape,
    :mission_statement,
    :name,
    :page_sections_config,
    :parent_origin_entity_id,
    :personality_traits,
    :picture_key,
    :picture_url,
    :podcast_button_color,
    :podcast_button_link,
    :podcast_button_text,
    :podcast_button_text_color,
    :podcast_button_visible,
    :podcast_config,
    :podcast_content_settings,
    :public_profile_config,
    :setup_progress_id,
    :slug,
    :social_links,
    :target_audience,
    :title,
    :tone_of_voice,
    :updated_at,
    :voice_config,
    :voice_settings,
    :website_content,
    :youtube_channel_data,
    :youtube_channel_id,
    :youtube_content_settings,
    :youtube_sync_settings
  ]

  @primitive_fields ~w(accent_colors ai_generated_summary appearance_config banner_key banner_url categories content_tabs_config content_themes core_values created_at description engagement_metrics extracted_content guardrails_settings id is_active is_featured is_public key_messaging last_website_scrape mission_statement name page_sections_config parent_origin_entity_id personality_traits picture_key picture_url podcast_button_color podcast_button_link podcast_button_text podcast_button_text_color podcast_button_visible podcast_config podcast_content_settings public_profile_config setup_progress_id slug social_links target_audience title tone_of_voice updated_at voice_config voice_settings website_content youtube_channel_data youtube_channel_id youtube_content_settings youtube_sync_settings)a

  @doc "All primitive field atoms — used when caller passes `fields: :all`."
  def primitive_fields, do: @primitive_fields

  @doc false
  @spec from_json(map() | nil) :: t() | nil
  def from_json(nil), do: nil

  def from_json(map) when is_map(map) do
    %__MODULE__{
      accent_colors: map["accent_colors"],
      ai_generated_summary: map["ai_generated_summary"],
      appearance_config: map["appearance_config"],
      banner_key: map["banner_key"],
      banner_url: map["banner_url"],
      categories: map["categories"],
      content_tabs_config: map["content_tabs_config"],
      content_themes: map["content_themes"],
      core_values: map["core_values"],
      created_at: OriginsSdk.Internal.decode_datetime(map["created_at"]),
      description: map["description"],
      engagement_metrics: map["engagement_metrics"],
      extracted_content: map["extracted_content"],
      guardrails_settings: map["guardrails_settings"],
      id: map["id"],
      is_active: map["is_active"],
      is_featured: map["is_featured"],
      is_public: map["is_public"],
      key_messaging: map["key_messaging"],
      last_website_scrape: OriginsSdk.Internal.decode_datetime(map["last_website_scrape"]),
      mission_statement: map["mission_statement"],
      name: map["name"],
      page_sections_config: map["page_sections_config"],
      parent_origin_entity_id: map["parent_origin_entity_id"],
      personality_traits: map["personality_traits"],
      picture_key: map["picture_key"],
      picture_url: map["picture_url"],
      podcast_button_color: map["podcast_button_color"],
      podcast_button_link: map["podcast_button_link"],
      podcast_button_text: map["podcast_button_text"],
      podcast_button_text_color: map["podcast_button_text_color"],
      podcast_button_visible: map["podcast_button_visible"],
      podcast_config: map["podcast_config"],
      podcast_content_settings: map["podcast_content_settings"],
      public_profile_config: map["public_profile_config"],
      setup_progress_id: map["setup_progress_id"],
      slug: map["slug"],
      social_links: map["social_links"],
      target_audience: map["target_audience"],
      title: map["title"],
      tone_of_voice: map["tone_of_voice"],
      updated_at: OriginsSdk.Internal.decode_datetime(map["updated_at"]),
      voice_config: map["voice_config"],
      voice_settings: map["voice_settings"],
      website_content: map["website_content"],
      youtube_channel_data: map["youtube_channel_data"],
      youtube_channel_id: map["youtube_channel_id"],
      youtube_content_settings: map["youtube_content_settings"],
      youtube_sync_settings: map["youtube_sync_settings"]
    }
  end
end
